version: "3.9"
services:
  app:
    build:
      ./infra/php
    volumes:
      - ./img-voting-kun:/work

  web:
    image: nginx:stable
    ports:
      - 60080:80
    volumes:
      - ./img-voting-kun:/work
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /work

  db:
    build: ./infra/mysql
    ports:
      - 33060:336
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: